// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                    = require("bs-jest/lib/js/src/jest.js");
var Index                   = require("../src/index.js");
var Utils                   = require("../src/utils.js");
var Pervasives              = require("bs-platform/lib/js/pervasives.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function defaultSystem_000() {
  return /* () */0;
}

function defaultSystem_001(_, _$1) {
  return /* () */0;
}

function defaultSystem_002() {
  return "";
}

function defaultSystem_003() {
  return "";
}

function defaultSystem_004() {
  return /* false */0;
}

var defaultSystem = /* record */[
  defaultSystem_000,
  defaultSystem_001,
  defaultSystem_002,
  defaultSystem_003,
  defaultSystem_004
];

describe("brewery help", (function () {
        var expectedFirstLineOutput = "Hi from brewery 🍻  here some help";
        Jest.test("it returns help", (function () {
                var logs = [""];
                var system_000 = function (s) {
                  logs[0] = s;
                  return /* () */0;
                };
                var system_001 = defaultSystem_001;
                var system_002 = defaultSystem_002;
                var system_003 = defaultSystem_003;
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "help"
                    ]);
                return Jest.Expect[/* toContainString */11](expectedFirstLineOutput)(Jest.Expect[/* expect */0](logs[0]));
              }));
        return Jest.test("it returns help when no argument is passed", (function () {
                      var logs = [""];
                      var system_000 = function (s) {
                        logs[0] = s;
                        return /* () */0;
                      };
                      var system_001 = defaultSystem_001;
                      var system_002 = defaultSystem_002;
                      var system_003 = defaultSystem_003;
                      var system_004 = defaultSystem_004;
                      var system = /* record */[
                        system_000,
                        system_001,
                        system_002,
                        system_003,
                        system_004
                      ];
                      Index.run(system, /* array */[
                            "node",
                            "program"
                          ]);
                      return Jest.Expect[/* toContainString */11](expectedFirstLineOutput)(Jest.Expect[/* expect */0](logs[0]));
                    }));
      }));

describe("brewery init", (function () {
        Jest.test("installs brew when it's not there", (function () {
                var installBrew = [/* false */0];
                var installCask = [/* false */0];
                var system_000 = defaultSystem_000;
                var system_001 = defaultSystem_001;
                var system_002 = defaultSystem_002;
                var system_003 = function (command) {
                  if (command === "brew --version") {
                    throw [
                          Caml_builtin_exceptions.assert_failure,
                          [
                            "command_test.re",
                            65,
                            34
                          ]
                        ];
                  } else if (command === Index.installBrewScript) {
                    installBrew[0] = /* true */1;
                    return "install script output";
                  } else if (command === Index.installCaskScript) {
                    installCask[0] = /* true */1;
                    return "install script output";
                  } else {
                    switch (command) {
                      case "brew cask list" : 
                          return "3\n4\n";
                      case "brew leaves" : 
                          return "first\nsecond\n";
                      default:
                        return "";
                    }
                  }
                };
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "init"
                    ]);
                return Jest.Expect[/* toEqual */12](/* tuple */[
                              /* true */1,
                              /* true */1
                            ])(Jest.Expect[/* expect */0](/* tuple */[
                                installBrew[0],
                                installCask[0]
                              ]));
              }));
        Jest.test("creates a .breweryfile.json with the returned brew formulas", (function () {
                var logs = [""];
                var writeFileRes = [/* tuple */[
                    "",
                    ""
                  ]];
                var system_000 = function (s) {
                  logs[0] = s;
                  return /* () */0;
                };
                var system_001 = function (path, content) {
                  writeFileRes[0] = /* tuple */[
                    path,
                    content
                  ];
                  return /* () */0;
                };
                var system_002 = defaultSystem_002;
                var system_003 = function (command) {
                  switch (command) {
                    case "brew --version" : 
                        return "brew already installed";
                    case "brew cask list" : 
                        return "3\n4\n";
                    case "brew leaves" : 
                        return "first\nsecond\n";
                    default:
                      return "";
                  }
                };
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "init"
                    ]);
                var match = Utils.jsonStringfy({
                      cask: /* array */[
                        "3",
                        "4"
                      ],
                      brew: /* array */[
                        "first",
                        "second"
                      ]
                    });
                var breweryfile = match ? match[0] : "";
                return Jest.Expect[/* toEqual */12](/* tuple */[
                              /* tuple */[
                                Index.breweryfilePath,
                                breweryfile
                              ],
                              ".breweryfile.json created"
                            ])(Jest.Expect[/* expect */0](/* tuple */[
                                writeFileRes[0],
                                logs[0]
                              ]));
              }));
        Jest.test("returns an error when brew leaves throws and does not write .breweryfile", (function () {
                var logs = [""];
                var writeFileRes = [/* tuple */[
                    "",
                    ""
                  ]];
                var system_000 = function (s) {
                  logs[0] = s;
                  return /* () */0;
                };
                var system_001 = function (path, content) {
                  writeFileRes[0] = /* tuple */[
                    path,
                    content
                  ];
                  return /* () */0;
                };
                var system_002 = defaultSystem_002;
                var system_003 = function (command) {
                  switch (command) {
                    case "brew --version" : 
                        return "brew already installed";
                    case "brew cask list" : 
                        return "3\n4\n";
                    case "brew leaves" : 
                        throw [
                              Caml_builtin_exceptions.assert_failure,
                              [
                                "command_test.re",
                                126,
                                31
                              ]
                            ];
                    default:
                      return "";
                  }
                };
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "init"
                    ]);
                return Jest.Expect[/* toEqual */12](/* tuple */[
                              /* tuple */[
                                "",
                                ""
                              ],
                              "error getting installed formulas"
                            ])(Jest.Expect[/* expect */0](/* tuple */[
                                writeFileRes[0],
                                logs[0]
                              ]));
              }));
        Jest.test("returns an error when brew cask install throws and does not write .breweryfile", (function () {
                var logs = [""];
                var writeFileRes = [/* tuple */[
                    "",
                    ""
                  ]];
                var system_000 = function (s) {
                  logs[0] = s;
                  return /* () */0;
                };
                var system_001 = function (path, content) {
                  writeFileRes[0] = /* tuple */[
                    path,
                    content
                  ];
                  return /* () */0;
                };
                var system_002 = defaultSystem_002;
                var system_003 = function (command) {
                  switch (command) {
                    case "brew --version" : 
                        return "brew already installed";
                    case "brew cask list" : 
                        throw [
                              Caml_builtin_exceptions.assert_failure,
                              [
                                "command_test.re",
                                151,
                                34
                              ]
                            ];
                    case "brew leaves" : 
                        return "3\n4\n";
                    default:
                      return "";
                  }
                };
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "init"
                    ]);
                return Jest.Expect[/* toEqual */12](/* tuple */[
                              /* tuple */[
                                "",
                                ""
                              ],
                              "error getting installed formulas"
                            ])(Jest.Expect[/* expect */0](/* tuple */[
                                writeFileRes[0],
                                logs[0]
                              ]));
              }));
        return Jest.test("returns an error if .breweryfile.json is already there", (function () {
                      var logs = [""];
                      var writeFileRes = [/* tuple */[
                          "",
                          ""
                        ]];
                      var system_000 = function (s) {
                        logs[0] = s;
                        return /* () */0;
                      };
                      var system_001 = function (path, content) {
                        writeFileRes[0] = /* tuple */[
                          path,
                          content
                        ];
                        return /* () */0;
                      };
                      var system_002 = defaultSystem_002;
                      var system_003 = defaultSystem_003;
                      var system_004 = function (path) {
                        if (path === Index.breweryfilePath) {
                          return /* true */1;
                        } else {
                          throw [
                                Caml_builtin_exceptions.assert_failure,
                                [
                                  "command_test.re",
                                  174,
                                  19
                                ]
                              ];
                        }
                      };
                      var system = /* record */[
                        system_000,
                        system_001,
                        system_002,
                        system_003,
                        system_004
                      ];
                      Index.run(system, /* array */[
                            "node",
                            "program",
                            "init"
                          ]);
                      return Jest.Expect[/* toEqual */12](/* tuple */[
                                    /* tuple */[
                                      "",
                                      ""
                                    ],
                                    Index.breweryfilePath + " exists already"
                                  ])(Jest.Expect[/* expect */0](/* tuple */[
                                      writeFileRes[0],
                                      logs[0]
                                    ]));
                    }));
      }));

describe("brewery install", (function () {
        var res = Utils.jsonStringfy({
              cask: /* array */["3"],
              brew: /* array */[
                "first",
                "second"
              ]
            });
        var initialBrewery = res ? res[0] : "error";
        Jest.test("installs brew when it's not there", (function () {
                var installBrew = [/* false */0];
                var installCask = [/* false */0];
                var system_000 = defaultSystem_000;
                var system_001 = defaultSystem_001;
                var system_002 = defaultSystem_002;
                var system_003 = function (command) {
                  if (command === "brew --version") {
                    throw [
                          Caml_builtin_exceptions.assert_failure,
                          [
                            "command_test.re",
                            207,
                            34
                          ]
                        ];
                  } else if (command === Index.installBrewScript) {
                    installBrew[0] = /* true */1;
                    return "install script output";
                  } else if (command === Index.installCaskScript) {
                    installCask[0] = /* true */1;
                    return "install script output";
                  } else {
                    switch (command) {
                      case "brew cask list" : 
                          return "3\n4\n";
                      case "brew leaves" : 
                          return "first\nsecond\n";
                      default:
                        return "";
                    }
                  }
                };
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "install"
                    ]);
                return Jest.Expect[/* toEqual */12](/* tuple */[
                              /* true */1,
                              /* true */1
                            ])(Jest.Expect[/* expect */0](/* tuple */[
                                installBrew[0],
                                installCask[0]
                              ]));
              }));
        Jest.test("adds brew formula to .breweryfile.json", (function () {
                var logs = [""];
                var writeFileRes = [/* tuple */[
                    "",
                    ""
                  ]];
                var readFileRes = [""];
                var system_000 = function (s) {
                  logs[0] = s;
                  return /* () */0;
                };
                var system_001 = function (path, content) {
                  writeFileRes[0] = /* tuple */[
                    path,
                    content
                  ];
                  return /* () */0;
                };
                var system_002 = function (path) {
                  readFileRes[0] = path;
                  return initialBrewery;
                };
                var system_003 = function (command) {
                  if (command === "brew --version") {
                    return "brew already installed";
                  } else {
                    return "";
                  }
                };
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "install",
                      "yarn"
                    ]);
                var match = Utils.jsonStringfy({
                      cask: /* array */["3"],
                      brew: /* array */[
                        "first",
                        "second",
                        "yarn"
                      ]
                    });
                var breweryfile = match ? match[0] : "";
                return Jest.Expect[/* toEqual */12](/* tuple */[
                              /* tuple */[
                                Index.breweryfilePath,
                                breweryfile
                              ],
                              ".breweryfile.json updated"
                            ])(Jest.Expect[/* expect */0](/* tuple */[
                                writeFileRes[0],
                                logs[0]
                              ]));
              }));
        Jest.test("adds cask formula to .breweryfile.json", (function () {
                var logs = [""];
                var writeFileRes = [/* tuple */[
                    "",
                    ""
                  ]];
                var readFileRes = [""];
                var system_000 = function (s) {
                  logs[0] = s;
                  return /* () */0;
                };
                var system_001 = function (path, content) {
                  writeFileRes[0] = /* tuple */[
                    path,
                    content
                  ];
                  return /* () */0;
                };
                var system_002 = function (path) {
                  readFileRes[0] = path;
                  return initialBrewery;
                };
                var system_003 = function (command) {
                  if (command === "brew --version") {
                    return "brew already installed";
                  } else {
                    return "";
                  }
                };
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "install",
                      "cask",
                      "yay"
                    ]);
                var match = Utils.jsonStringfy({
                      cask: /* array */[
                        "3",
                        "yay"
                      ],
                      brew: /* array */[
                        "first",
                        "second"
                      ]
                    });
                var breweryfile = match ? match[0] : "";
                return Jest.Expect[/* toEqual */12](/* tuple */[
                              /* tuple */[
                                Index.breweryfilePath,
                                breweryfile
                              ],
                              ".breweryfile.json updated"
                            ])(Jest.Expect[/* expect */0](/* tuple */[
                                writeFileRes[0],
                                logs[0]
                              ]));
              }));
        Jest.test("installs all formulas from .breweryfile.json when no arguments are passed in", (function () {
                var res = Utils.jsonStringfy({
                      cask: /* array */[
                        "3",
                        "foo"
                      ],
                      brew: /* array */[
                        "first",
                        "boom"
                      ]
                    });
                var initialBrewery = res ? res[0] : "error";
                var logs = [/* [] */0];
                var readFileRes = [""];
                var installedFormulas = [/* [] */0];
                var system_000 = function (s) {
                  logs[0] = Pervasives.$at(logs[0], /* :: */[
                        s,
                        /* [] */0
                      ]);
                  return /* () */0;
                };
                var system_001 = defaultSystem_001;
                var system_002 = function (path) {
                  readFileRes[0] = path;
                  return initialBrewery;
                };
                var system_003 = function (command) {
                  if (command === "brew --version") {
                    return "brew already installed";
                  } else {
                    installedFormulas[0] = Pervasives.$at(installedFormulas[0], /* :: */[
                          command,
                          /* [] */0
                        ]);
                    return "";
                  }
                };
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "install"
                    ]);
                return Jest.Expect[/* toEqual */12](/* tuple */[
                              /* :: */[
                                "first installed successfully",
                                /* :: */[
                                  "boom installed successfully",
                                  /* :: */[
                                    "3 installed successfully",
                                    /* :: */[
                                      "foo installed successfully",
                                      /* :: */[
                                        "All formulas installed",
                                        /* [] */0
                                      ]
                                    ]
                                  ]
                                ]
                              ],
                              /* :: */[
                                "brew install first",
                                /* :: */[
                                  "brew install boom",
                                  /* :: */[
                                    "brew cask install 3",
                                    /* :: */[
                                      "brew cask install foo",
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ]
                            ])(Jest.Expect[/* expect */0](/* tuple */[
                                logs[0],
                                installedFormulas[0]
                              ]));
              }));
        Jest.test("logs the formulas that failed to be installed", (function () {
                var res = Utils.jsonStringfy({
                      cask: /* array */[
                        "3",
                        "foo"
                      ],
                      brew: /* array */[
                        "first",
                        "boom"
                      ]
                    });
                var initialBrewery = res ? res[0] : "error";
                var logs = [/* [] */0];
                var readFileRes = [""];
                var installedFormulas = [/* [] */0];
                var system_000 = function (s) {
                  logs[0] = Pervasives.$at(logs[0], /* :: */[
                        s,
                        /* [] */0
                      ]);
                  return /* () */0;
                };
                var system_001 = defaultSystem_001;
                var system_002 = function (path) {
                  readFileRes[0] = path;
                  return initialBrewery;
                };
                var system_003 = function (command) {
                  if (command === "brew --version") {
                    return "brew already installed";
                  } else if (command !== "brew cask install 3") {
                    installedFormulas[0] = Pervasives.$at(installedFormulas[0], /* :: */[
                          command,
                          /* [] */0
                        ]);
                    return "";
                  } else {
                    installedFormulas[0] = Pervasives.$at(installedFormulas[0], /* :: */[
                          command,
                          /* [] */0
                        ]);
                    throw Pervasives.Exit;
                  }
                };
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "install"
                    ]);
                return Jest.Expect[/* toEqual */12](/* tuple */[
                              /* :: */[
                                "first installed successfully",
                                /* :: */[
                                  "boom installed successfully",
                                  /* :: */[
                                    "Error installing 3 formula",
                                    /* :: */[
                                      "foo installed successfully",
                                      /* :: */[
                                        "Not all formulas installed",
                                        /* [] */0
                                      ]
                                    ]
                                  ]
                                ]
                              ],
                              /* :: */[
                                "brew install first",
                                /* :: */[
                                  "brew install boom",
                                  /* :: */[
                                    "brew cask install 3",
                                    /* :: */[
                                      "brew cask install foo",
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ]
                            ])(Jest.Expect[/* expect */0](/* tuple */[
                                logs[0],
                                installedFormulas[0]
                              ]));
              }));
        Jest.test("doesn't add cask formula to .breweryfile.json when already there", (function () {
                var res = Utils.jsonStringfy({
                      cask: /* array */[
                        "3",
                        "yay"
                      ],
                      brew: /* array */[
                        "first",
                        "second"
                      ]
                    });
                var initialBrewery = res ? res[0] : "error";
                var writeFileRes = [/* tuple */[
                    "",
                    ""
                  ]];
                var system_000 = defaultSystem_000;
                var system_001 = function (path, content) {
                  writeFileRes[0] = /* tuple */[
                    path,
                    content
                  ];
                  return /* () */0;
                };
                var system_002 = function () {
                  return initialBrewery;
                };
                var system_003 = function (command) {
                  if (command === "brew --version") {
                    return "brew already installed";
                  } else {
                    return "";
                  }
                };
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "install",
                      "cask",
                      "yay"
                    ]);
                var match = Utils.jsonStringfy({
                      cask: /* array */[
                        "3",
                        "yay"
                      ],
                      brew: /* array */[
                        "first",
                        "second"
                      ]
                    });
                var breweryfile = match ? match[0] : "";
                return Jest.Expect[/* toEqual */12](/* tuple */[
                              Index.breweryfilePath,
                              breweryfile
                            ])(Jest.Expect[/* expect */0](writeFileRes[0]));
              }));
        return Jest.test("returns an error if .breweryfile.json isn't found", (function () {
                      var logs = [""];
                      var system_000 = function (s) {
                        logs[0] = s;
                        return /* () */0;
                      };
                      var system_001 = defaultSystem_001;
                      var system_002 = function () {
                        throw Caml_builtin_exceptions.not_found;
                      };
                      var system_003 = defaultSystem_003;
                      var system_004 = defaultSystem_004;
                      var system = /* record */[
                        system_000,
                        system_001,
                        system_002,
                        system_003,
                        system_004
                      ];
                      Index.run(system, /* array */[
                            "node",
                            "program",
                            "install",
                            "foo"
                          ]);
                      return Jest.Expect[/* toEqual */12]("Error loading " + (String(Index.breweryfilePath) + ""))(Jest.Expect[/* expect */0](logs[0]));
                    }));
      }));

describe("brewery list", (function () {
        var res = Utils.jsonStringfy({
              cask: /* array */["3"],
              brew: /* array */[
                "first",
                "second"
              ]
            });
        var breweryConf = res ? res[0] : "error";
        Jest.test("shows installed formulas", (function () {
                var logs = [""];
                var readFileRes = [""];
                var system_000 = function (s) {
                  logs[0] = s;
                  return /* () */0;
                };
                var system_001 = defaultSystem_001;
                var system_002 = function (path) {
                  readFileRes[0] = path;
                  return breweryConf;
                };
                var system_003 = defaultSystem_003;
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "list"
                    ]);
                return Jest.Expect[/* toEqual */12](/* tuple */[
                              Index.breweryfilePath,
                              breweryConf
                            ])(Jest.Expect[/* expect */0](/* tuple */[
                                readFileRes[0],
                                logs[0]
                              ]));
              }));
        return Jest.test("returns an error if .breweryfile.json isn't found", (function () {
                      var logs = [""];
                      var system_000 = function (s) {
                        logs[0] = s;
                        return /* () */0;
                      };
                      var system_001 = defaultSystem_001;
                      var system_002 = function () {
                        throw Caml_builtin_exceptions.not_found;
                      };
                      var system_003 = defaultSystem_003;
                      var system_004 = defaultSystem_004;
                      var system = /* record */[
                        system_000,
                        system_001,
                        system_002,
                        system_003,
                        system_004
                      ];
                      Index.run(system, /* array */[
                            "node",
                            "program",
                            "list"
                          ]);
                      return Jest.Expect[/* toEqual */12]("Error loading " + (String(Index.breweryfilePath) + ""))(Jest.Expect[/* expect */0](logs[0]));
                    }));
      }));

describe("brewery uninstall", (function () {
        var toJson = function (brewery) {
          var res = Utils.jsonStringfy(brewery);
          if (res) {
            return res[0];
          } else {
            return "error";
          }
        };
        var initialBrewery = toJson({
              cask: /* array */[
                "3",
                "foo"
              ],
              brew: /* array */[
                "pluto",
                "tom"
              ]
            });
        Jest.test("removes the formula", (function () {
                var logs = [""];
                var writeFileRes = [/* tuple */[
                    "",
                    ""
                  ]];
                var system_000 = function (s) {
                  logs[0] = s;
                  return /* () */0;
                };
                var system_001 = function (path, content) {
                  writeFileRes[0] = /* tuple */[
                    path,
                    content
                  ];
                  return /* () */0;
                };
                var system_002 = function (path) {
                  var match = +(path === Index.breweryfilePath);
                  if (match !== 0) {
                    return initialBrewery;
                  } else {
                    return "";
                  }
                };
                var system_003 = defaultSystem_003;
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                var expectedBrewery = toJson({
                      cask: /* array */[
                        "3",
                        "foo"
                      ],
                      brew: /* array */["tom"]
                    });
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "uninstall",
                      "pluto"
                    ]);
                return Jest.Expect[/* toEqual */12](/* tuple */[
                              ".breweryfile.json updated",
                              /* tuple */[
                                Index.breweryfilePath,
                                expectedBrewery
                              ]
                            ])(Jest.Expect[/* expect */0](/* tuple */[
                                logs[0],
                                writeFileRes[0]
                              ]));
              }));
        Jest.test("removes the cask formula", (function () {
                var logs = [""];
                var writeFileRes = [/* tuple */[
                    "",
                    ""
                  ]];
                var system_000 = function (s) {
                  logs[0] = s;
                  return /* () */0;
                };
                var system_001 = function (path, content) {
                  writeFileRes[0] = /* tuple */[
                    path,
                    content
                  ];
                  return /* () */0;
                };
                var system_002 = function (path) {
                  var match = +(path === Index.breweryfilePath);
                  if (match !== 0) {
                    return initialBrewery;
                  } else {
                    return "";
                  }
                };
                var system_003 = defaultSystem_003;
                var system_004 = defaultSystem_004;
                var system = /* record */[
                  system_000,
                  system_001,
                  system_002,
                  system_003,
                  system_004
                ];
                var expectedBrewery = toJson({
                      cask: /* array */["3"],
                      brew: /* array */[
                        "pluto",
                        "tom"
                      ]
                    });
                Index.run(system, /* array */[
                      "node",
                      "program",
                      "uninstall",
                      "cask",
                      "foo"
                    ]);
                return Jest.Expect[/* toEqual */12](/* tuple */[
                              ".breweryfile.json updated",
                              /* tuple */[
                                Index.breweryfilePath,
                                expectedBrewery
                              ]
                            ])(Jest.Expect[/* expect */0](/* tuple */[
                                logs[0],
                                writeFileRes[0]
                              ]));
              }));
        return Jest.test("returns an error if .breweryfilePath.json isn't found", (function () {
                      var logs = [""];
                      var system_000 = function (s) {
                        logs[0] = s;
                        return /* () */0;
                      };
                      var system_001 = defaultSystem_001;
                      var system_002 = function () {
                        throw Caml_builtin_exceptions.not_found;
                      };
                      var system_003 = defaultSystem_003;
                      var system_004 = defaultSystem_004;
                      var system = /* record */[
                        system_000,
                        system_001,
                        system_002,
                        system_003,
                        system_004
                      ];
                      Index.run(system, /* array */[
                            "node",
                            "program",
                            "uninstall",
                            "pluto"
                          ]);
                      return Jest.Expect[/* toEqual */12]("Error loading " + (String(Index.breweryfilePath) + ""))(Jest.Expect[/* expect */0](logs[0]));
                    }));
      }));

exports.defaultSystem = defaultSystem;
/*  Not a pure module */
