// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List    = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");

function make() {
  return /* record */[
          /* cask : [] */0,
          /* brew : [] */0
        ];
}

function toDict(brewConfig) {
  var dict = { };
  var packages = function (packages$1) {
    return $$Array.of_list(List.map((function (param) {
                      return param[/* name */0];
                    }), packages$1));
  };
  dict["cask"] = packages(brewConfig[/* cask */0]);
  dict["brew"] = packages(brewConfig[/* brew */1]);
  return dict;
}

exports.make   = make;
exports.toDict = toDict;
/* No side effect */
