// Generated by BUCKLESCRIPT VERSION 2.1.1, PLEASE EDIT WITH CARE
'use strict';


function makeBuffer(a) {
  return a;
}

function stringOfBuffer(buffer) {
  return buffer.toString();
}

function jsonStringfy(a) {
  try {
    return /* Some */[JSON.stringify(a, null, 2)];
  }
  catch (exn){
    return /* None */0;
  }
}

exports.makeBuffer     = makeBuffer;
exports.stringOfBuffer = stringOfBuffer;
exports.jsonStringfy   = jsonStringfy;
/* No side effect */
